version: 2
models:
  - name: sales_facts
    columns:
      - name: sale_id
        tests: [unique, not_null]
      - name: product_id
        tests:
          - relationships:
              arguments:
                to: ref('product_dimension')
                field: product_id
  - name: daily_store_mart
    columns:
      - name: revenue
        tests: [not_null]
