name: cg_lakehouse
version: 1.0.0
config-version: 2

profile: cg_lakehouse

on-run-start:
  - "{{ ducklake__bootstrap() }}"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  cg_lakehouse:
    +materialized: table
    bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]
      +quoting:
        identifier: false
    silver:
      +schema: silver
      +tags: ["silver"]
    gold:
      +schema: gold
      +tags: ["gold"]
      +persist_docs: { relation: true, columns: true }
    marts_postgres:
      +schema: marts
      +tags: ["mart"]
      +materialized: table
