cascade:
  target: dev
  outputs:
    dev:
      type: trino
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '10005') | int }}"
      user: dbt
      catalog: iceberg_dev
      schema: bronze
      threads: 8

    prod:
      type: trino
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '10005') | int }}"
      user: dbt
      catalog: iceberg
      schema: bronze
      threads: 8

    postgres:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: "{{ env_var('POSTGRES_PORT', '10000') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: marts
      threads: 8
