cascade:
  target: ducklake
  outputs:
    ducklake:
      type: duckdb
      path: ":memory:"
      schema: "raw"
      threads: 8
      extensions: ["ducklake", "httpfs", "postgres", "json", "parquet"]
      # S3-compatible (MinIO)
      settings:
        s3_endpoint: "{{ env_var('MINIO_HOST', 'minio') }}:{{ env_var('MINIO_API_PORT', '9000') }}"
        s3_use_ssl: false
        s3_url_style: path
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
        s3_region: "{{ env_var('DUCKLAKE_REGION', 'us-east-1') }}"
        ducklake_max_retry_count: 200
        ducklake_retry_wait_ms: 150
        ducklake_retry_backoff: 2.5
      # Attach DuckLake catalog - secrets created in on-run-start hook
      # Note: attach happens AFTER on-run-start, so secrets will be available
    postgres:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: marts
      threads: 8
