cascade:
  target: dev
  outputs:
    dev:
      type: trino
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: dbt
      catalog: iceberg
      schema: bronze
      threads: 8
      session_properties:
        nessie.reference: dev

    prod:
      type: trino
      host: "{{ env_var('TRINO_HOST', 'trino') }}"
      port: "{{ env_var('TRINO_PORT', '8080') | int }}"
      user: dbt
      catalog: iceberg
      schema: bronze
      threads: 8
      session_properties:
        nessie.reference: main

    postgres:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: marts
      threads: 8
