"""Authoritative security classification for API entry points.

The manifest is deliberately kept beside the API package rather than spread
across route decorators.  Every route that FastAPI exposes must have one
classification, and protected classifications always resolve a concrete
resource before the handler is called.
"""

from __future__ import annotations

import json
import os
from uuid import uuid4
from dataclasses import dataclass, replace
from typing import Any, Iterable

from fastapi import HTTPException, Request
from starlette.routing import Match
from starlette.responses import JSONResponse

from phlo.capabilities import DecisionContext, ResourceRef
from phlo.logging import bind_context, clear_context, get_logger
from phlo.rbac.models import CanonicalAction
from phlo.security import enforce, is_regulated

from phlo_api.api.authentication import get_request_principal
from phlo_api.api.authorization import (
    create_decision_context,
    get_request_correlation_id,
    get_authorization_backend,
    resolve_request_principal,
)


@dataclass(frozen=True)
class OperationSpec:
    """Security classification for one externally reachable operation."""

    operation_name: str
    surface: str
    action: str
    resource_type: str
    public: bool = False
    resource_keys: tuple[str, ...] = ()
    methods: tuple[str, ...] = ()
    path: str | None = None
    endpoint: str | None = None


HTTP_ROUTE_KEY_MANIFEST: dict[tuple[str, str], OperationSpec] = {}
logger = get_logger(__name__)


def _specs(
    names: Iterable[str],
    *,
    action: str,
    resource_type: str,
    resource_keys: tuple[str, ...] = (),
) -> tuple[OperationSpec, ...]:
    return tuple(
        OperationSpec(
            operation_name=name,
            surface="http",
            action=action,
            resource_type=resource_type,
            resource_keys=resource_keys,
        )
        for name in names
    )


# This is the only route-name-to-policy mapping in phlo-api.  The startup
# validator compares it with the actual FastAPI route table, including docs
# routes generated by FastAPI itself.
HTTP_ROUTE_DECLARATIONS: tuple[OperationSpec, ...] = (
    OperationSpec(
        operation_name="health",
        surface="http",
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
        public=True,
    ),
    *_specs(
        (
            "openapi",
            "swagger_ui_html",
            "swagger_ui_redirect",
            "redoc_html",
            "get_config",
            "get_plugins",
            "get_plugins_by_type",
            "get_plugin_info",
            "get_registry",
            "get_api_backends",
            "get_api_backend_info",
            "get_contracts",
            "get_contract",
            "list_templates",
            "list_workflows",
            "run_doctor",
        ),
        action=CanonicalAction.PLATFORM_METADATA_READ.value,
        resource_type="platform_metadata",
        resource_keys=("name", "plugin_type", "table_name"),
    ),
    *_specs(
        ("create_workflow", "validate_workflow", "validate_schema", "lint_project"),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="object",
        resource_keys=("workflow_path", "schema_path", "target"),
    ),
    *_specs(
        ("get_services", "get_service_info"),
        action=CanonicalAction.SERVICE_READ.value,
        resource_type="service",
        resource_keys=("name",),
    ),
    *_specs(
        ("get_maintenance_status", "get_maintenance_metrics"),
        action=CanonicalAction.MAINTENANCE_READ.value,
        resource_type="maintenance",
    ),
    *_specs(
        (
            "get_health_summary",
            "get_service_status",
            "get_platform_metrics",
            "get_recent_alerts",
            "get_dashboard_links",
            "get_logs_query_link",
            "get_metrics_query_link",
            "get_run_trace_spans",
            "get_trace_spans",
        ),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
        resource_keys=("run_id",),
    ),
    *_specs(
        (
            "query_logs",
            "query_run_logs",
            "stream_run_logs",
            "query_asset_logs",
            "get_log_labels",
            "get_observatory_logs",
            "get_observatory_log_facets",
        ),
        action=CanonicalAction.AUDIT_READ.value,
        resource_type="audit",
        resource_keys=("run_id", "asset_key", "asset_key_path"),
    ),
    *_specs(
        ("check_connection",),
        action=CanonicalAction.OBSERVABILITY_READ.value,
        resource_type="observability",
    ),
    *_specs(
        (
            "get_observatory_overview",
            "get_observatory_capabilities",
            "get_observatory_surface_capabilities",
            "get_observatory_capability_inventory",
            "get_observatory_services",
            "get_observatory_service_detail",
            "get_observatory_operations",
            "get_observatory_operation_agent_context",
            "get_observatory_operation_detail",
            "get_observatory_storage",
            "get_observatory_observability",
            "get_observatory_governance",
            "get_observatory_apis",
            "get_observatory_bi",
            "get_observatory_search",
            "get_observatory_extensions",
            "get_observatory_extension_manifests",
            "get_observatory_extension_asset",
            "get_observatory_extension_detail",
            "get_observatory_workflow_wizard",
        ),
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
        resource_keys=("service_id", "operation_id", "name", "extension_id"),
    ),
    *_specs(
        (
            "get_observatory_preferences",
            "get_observatory_settings",
            "get_observatory_dataset_workflow_config",
        ),
        action=CanonicalAction.SETTINGS_READ.value,
        resource_type="settings",
        resource_keys=("name", "dataset_id"),
    ),
    *_specs(
        (
            "get_observatory_runs",
            "get_observatory_run_status",
        ),
        action=CanonicalAction.RUN_READ.value,
        resource_type="run",
        resource_keys=("run_id",),
    ),
    *_specs(
        ("post_observatory_run_retry", "post_observatory_run_cancel"),
        action=CanonicalAction.RUN_MANAGE.value,
        resource_type="run",
        resource_keys=("run_id",),
    ),
    *_specs(
        (
            "get_observatory_assets",
            "get_observatory_asset_graph",
            "get_observatory_asset_neighbors",
            "get_observatory_asset_impact",
            "get_observatory_asset_materializations",
            "get_observatory_asset_partitions",
            "get_observatory_asset_detail",
        ),
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
        resource_keys=("asset_id",),
    ),
    *_specs(
        ("post_observatory_asset_materialize", "post_observatory_asset_backfill"),
        action=CanonicalAction.ASSET_EXECUTE.value,
        resource_type="asset",
        resource_keys=("asset_id",),
    ),
    *_specs(
        (
            "get_observatory_datasets",
            "get_observatory_dataset_profile",
            "get_observatory_tables",
            "get_observatory_table_preview",
            "post_observatory_schema_diff",
            "get_observatory_quality",
            "get_observatory_pipelines",
        ),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("dataset_id", "table_id", "table_name", "pipeline_id", "check_id"),
    ),
    *_specs(
        ("get_observatory_stage_diff",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("source_table_id", "target_table_id"),
    ),
    *_specs(
        ("get_observatory_row_journey",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("table_id", "row_id"),
    ),
    *_specs(
        ("get_observatory_quality_detail",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("check_id",),
    ),
    *_specs(
        (
            "post_observatory_query",
            "post_observatory_contributing_rows_query",
            "post_observatory_contributing_rows_page",
        ),
        action=CanonicalAction.DATASET_QUERY.value,
        resource_type="dataset",
        resource_keys=("dataset_id", "table_id", "table_name"),
    ),
    *_specs(
        ("get_observatory_saved_queries",),
        action=CanonicalAction.DATASET_READ.value,
        resource_type="dataset",
        resource_keys=("dataset_id", "table_id"),
    ),
    *_specs(
        ("post_observatory_saved_query",),
        action=CanonicalAction.DATASET_WRITE.value,
        resource_type="dataset",
        resource_keys=("dataset_id", "table_id", "table_name"),
    ),
    *_specs(
        ("get_observatory_branches", "get_observatory_branch_detail"),
        action=CanonicalAction.CATALOG_READ.value,
        resource_type="catalog",
        resource_keys=("branch_name",),
    ),
    *_specs(
        ("post_observatory_branch_action",),
        action=CanonicalAction.CATALOG_MANAGE.value,
        resource_type="catalog",
        resource_keys=("branch_name", "target"),
    ),
    *_specs(
        ("get_observatory_extension_settings",),
        action=CanonicalAction.SETTINGS_READ.value,
        resource_type="settings",
        resource_keys=("name",),
    ),
    *_specs(
        ("put_observatory_extension_settings", "put_observatory_preferences"),
        action=CanonicalAction.SETTINGS_MANAGE.value,
        resource_type="settings",
        resource_keys=("name",),
    ),
    *_specs(
        ("put_observatory_dataset_workflow_config",),
        action=CanonicalAction.SETTINGS_MANAGE.value,
        resource_type="settings",
        resource_keys=("dataset_id", "name"),
    ),
    *_specs(
        ("post_observatory_workflow_wizard_proposal", "post_observatory_workflow_wizard_action"),
        action=CanonicalAction.OBJECT_WRITE.value,
        resource_type="object",
        resource_keys=("proposal_id", "workflow_id", "target", "path"),
    ),
    *_specs(
        ("post_observatory_action", "post_observatory_package_install"),
        action=CanonicalAction.SERVICE_MANAGE.value,
        resource_type="service",
        resource_keys=("service_id", "action_id", "name", "package"),
    ),
)


def _build_http_manifest(declarations: tuple[OperationSpec, ...]) -> dict[str, OperationSpec]:
    """Index ordered declarations while rejecting duplicates before indexing."""
    manifest: dict[str, OperationSpec] = {}
    for spec in declarations:
        if spec.operation_name in manifest:
            raise RuntimeError(f"Duplicate HTTP security manifest operation: {spec.operation_name}")
        manifest[spec.operation_name] = spec
    return manifest


HTTP_ROUTE_MANIFEST = _build_http_manifest(HTTP_ROUTE_DECLARATIONS)

# Explicitly catalog non-FastAPI entry points that are reachable in the v1
# stack.  These aren't silently made public by virtue of living in another
# service; each operation is still mapped to canonical policy.
GRAPHQL_OPERATION_MANIFEST: tuple[OperationSpec, ...] = (
    OperationSpec(
        operation_name="hasura.graphql.query",
        surface="graphql",
        endpoint="hasura:/v1/graphql",
        action=CanonicalAction.DATASET_QUERY.value,
        resource_type="dataset",
    ),
    OperationSpec(
        operation_name="hasura.graphql.mutation",
        surface="graphql",
        endpoint="hasura:/v1/graphql",
        action=CanonicalAction.DATASET_WRITE.value,
        resource_type="dataset",
    ),
    OperationSpec(
        operation_name="hasura.graphql.subscription",
        surface="graphql",
        endpoint="hasura:/v1/graphql",
        action=CanonicalAction.DATASET_QUERY.value,
        resource_type="dataset",
    ),
    OperationSpec(
        operation_name="hasura.graphql.introspection",
        surface="graphql",
        endpoint="hasura:/v1/graphql",
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
    ),
    OperationSpec(
        operation_name="dagster.graphql.query",
        surface="graphql",
        endpoint="dagster-webserver:/graphql",
        action=CanonicalAction.ASSET_READ.value,
        resource_type="asset",
    ),
    OperationSpec(
        operation_name="dagster.graphql.mutation",
        surface="graphql",
        endpoint="dagster-webserver:/graphql",
        action=CanonicalAction.RUN_EXECUTE.value,
        resource_type="run",
    ),
    OperationSpec(
        operation_name="dagster.graphql.introspection",
        surface="graphql",
        endpoint="dagster-webserver:/graphql",
        action=CanonicalAction.ADMIN_READ.value,
        resource_type="admin",
    ),
)

WEBSOCKET_OPERATION_MANIFEST: tuple[OperationSpec, ...] = (
    OperationSpec(
        operation_name="hasura.websocket.subscription",
        surface="websocket",
        endpoint="hasura:/v1/graphql",
        action=CanonicalAction.DATASET_QUERY.value,
        resource_type="dataset",
    ),
)

PUBLIC_HTTP_PATHS = frozenset({"/health"})


def _all_manifest_names() -> list[str]:
    names = list(HTTP_ROUTE_MANIFEST)
    names.extend(spec.operation_name for spec in GRAPHQL_OPERATION_MANIFEST)
    names.extend(spec.operation_name for spec in WEBSOCKET_OPERATION_MANIFEST)
    return names


def validate_manifest(app: Any) -> tuple[OperationSpec, ...]:
    """Validate the complete HTTP route table and return resolved entries."""
    duplicate_names = [
        name for name in _all_manifest_names() if _all_manifest_names().count(name) > 1
    ]
    if duplicate_names:
        raise RuntimeError(
            f"Duplicate security manifest operations: {sorted(set(duplicate_names))}"
        )

    actual_routes: list[tuple[str, str, Any]] = []
    for route in app.routes:
        methods = getattr(route, "methods", None)
        path = getattr(route, "path", None)
        name = getattr(route, "name", None)
        if methods and path and name:
            actual_routes.append((name, path, route))

    actual_name_counts: dict[str, int] = {}
    for name, _path, _route in actual_routes:
        actual_name_counts[name] = actual_name_counts.get(name, 0) + 1
    duplicate_route_names = sorted(name for name, count in actual_name_counts.items() if count > 1)
    if duplicate_route_names:
        raise RuntimeError(
            f"Duplicate HTTP route names in security manifest: {duplicate_route_names!r}"
        )
    manifest_names = set(HTTP_ROUTE_MANIFEST)
    missing = sorted(set(actual_name_counts) - manifest_names)
    stale = sorted(manifest_names - set(actual_name_counts))
    if missing or stale:
        raise RuntimeError(
            f"HTTP security manifest drift: unclassified={missing!r}, stale={stale!r}"
        )

    seen_routes: set[tuple[str, str]] = set()
    route_key_manifest: dict[tuple[str, str], OperationSpec] = {}
    resolved: list[OperationSpec] = []
    for name, path, route in actual_routes:
        spec = HTTP_ROUTE_MANIFEST[name]
        for method in sorted(route.methods):
            key = (method, path)
            if key in seen_routes:
                raise RuntimeError(
                    f"Duplicate HTTP security manifest operation for {method} {path}"
                )
            seen_routes.add(key)
            resolved_spec = OperationSpec(
                **{
                    **spec.__dict__,
                    "methods": tuple(sorted(route.methods)),
                    "path": path,
                }
            )
            route_key_manifest[key] = resolved_spec
            resolved.append(resolved_spec)

        if path in PUBLIC_HTTP_PATHS and not spec.public:
            # Health is the only intentionally anonymous route.  Keeping this
            # check explicit prevents a later route rename from widening it.
            if name != "health":
                raise RuntimeError(f"Unexpected public HTTP path in manifest: {path}")
        if spec.public and path not in PUBLIC_HTTP_PATHS:
            raise RuntimeError(f"Protected route incorrectly marked public: {path}")

    HTTP_ROUTE_KEY_MANIFEST.clear()
    HTTP_ROUTE_KEY_MANIFEST.update(route_key_manifest)
    return tuple(resolved)


def _route_for_request(app: Any, request: Request) -> tuple[OperationSpec, dict[str, str]] | None:
    for route in app.routes:
        methods = getattr(route, "methods", None)
        if not methods or request.method not in methods:
            continue
        match, child_scope = route.matches(request.scope)
        if match is Match.FULL:
            spec = HTTP_ROUTE_KEY_MANIFEST.get((request.method, getattr(route, "path", "")))
            if spec is None:
                return None
            return spec, child_scope.get("path_params", {})
    return None


async def _request_json(request: Request) -> Any:
    override = getattr(request.state, "_phlo_security_body_override", None)
    if override is not None:
        return override
    content_length = request.headers.get("content-length")
    if content_length and content_length.isdigit() and int(content_length) > 1_048_576:
        raise HTTPException(status_code=413, detail={"error": "request_too_large"})
    if request.headers.get("content-type", "").split(";", 1)[0].strip().lower() not in {
        "application/json",
        "application/graphql+json",
    }:
        return None
    try:
        raw = await request.body()
        return json.loads(raw) if raw else None
    except (UnicodeDecodeError, json.JSONDecodeError):
        return None


async def resolve_resource(
    request: Request,
    spec: OperationSpec,
    path_params: dict[str, str],
) -> ResourceRef:
    scoped_values = {key: path_params[key] for key in spec.resource_keys if path_params.get(key)}
    scoped_values.update(
        {
            key: request.query_params[key]
            for key in spec.resource_keys
            if request.query_params.get(key) and key not in scoped_values
        }
    )
    resource_id = "|".join(
        f"{key}={scoped_values[key]}" for key in spec.resource_keys if key in scoped_values
    )
    resource_id = resource_id or None
    body = None
    if resource_id is not None:
        # Path/query identity is authoritative.  For small JSON requests only,
        # reject a same-key body mismatch instead of silently authorizing one
        # resource while the handler acts on another.
        authoritative_keys = {key for key, value in path_params.items() if value}
        authoritative_keys.update(
            key for key in spec.resource_keys if request.query_params.get(key)
        )
        content_length = request.headers.get("content-length")
        if (
            authoritative_keys
            and content_length
            and content_length.isdigit()
            and int(content_length) <= 65_536
        ):
            body = await _request_json(request)
        if isinstance(body, dict):
            for key in authoritative_keys:
                candidate = body.get(key)
                authoritative_value = path_params.get(key) or request.query_params.get(key)
                if candidate is not None and str(candidate) != str(authoritative_value):
                    raise HTTPException(status_code=400, detail={"error": "ambiguous_resource"})
    else:
        body = await _request_json(request)
    if resource_id is None and body is not None:
        resource_id = (
            "|".join(
                f"{key}={body[key]}"
                for key in spec.resource_keys
                if isinstance(body, dict)
                and isinstance(body.get(key), (str, int))
                and str(body[key])
            )
            or None
        )
    return ResourceRef(
        resource_type=spec.resource_type,
        resource_id=resource_id or os.environ.get("PHLO_PROJECT_NAME", "project"),
        attributes={"project": os.environ.get("PHLO_PROJECT_NAME", "project")},
    )


def _raise_unauthorized() -> None:
    raise HTTPException(
        status_code=401,
        detail={"error": "unauthorized", "reason": "authentication_required"},
        headers={"WWW-Authenticate": "Bearer"},
    )


async def enforce_http_operation(
    request: Request,
    spec: OperationSpec,
    path_params: dict[str, str],
) -> None:
    """Authenticate and authorize a classified HTTP operation."""
    if spec.public:
        return

    if get_request_principal(request) is None:
        _raise_unauthorized()

    spec = await _specialize_operation(request, spec)
    resource = await resolve_resource(request, spec, path_params)
    principal = resolve_request_principal(request, require_auth=True)
    if principal is None:
        _raise_unauthorized()
    context: DecisionContext = create_decision_context(request)
    correlation_id = get_request_correlation_id(request)

    if is_regulated():
        result = enforce(
            principal=principal,
            action=spec.action,
            resource=resource,
            context=context,
            request_id=correlation_id,
            surface="phlo-api",
            correlation_id=correlation_id,
        )
        if result.variant == "error":
            raise HTTPException(
                status_code=503,
                detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
            )
        if not result.allowed:
            raise HTTPException(
                status_code=403,
                detail={"error": "forbidden", "reason": "access_denied"},
            )
        return

    backend = get_authorization_backend()
    if backend is None:
        raise HTTPException(
            status_code=503,
            detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
        )
    decision = backend.explain_decision(principal, spec.action, resource, context)
    if decision.reason_code == "backend_unavailable":
        raise HTTPException(
            status_code=503,
            detail={"error": "service_unavailable", "reason": "authorization_unavailable"},
        )
    if not decision.allowed:
        raise HTTPException(
            status_code=403,
            detail={"error": "forbidden", "reason": "access_denied"},
        )


async def _specialize_operation(request: Request, spec: OperationSpec) -> OperationSpec:
    """Resolve the action/resource pair for payload-dispatched operations."""
    if spec.operation_name != "post_observatory_action":
        return spec
    body = await _request_json(request)
    if not isinstance(body, dict):
        return spec
    action_id = body.get("action_id")
    if not isinstance(action_id, str) or not action_id:
        return spec

    if action_id.startswith("dataset:"):
        action = (
            CanonicalAction.DATASET_PUBLISH.value
            if action_id == "dataset:publish"
            else CanonicalAction.DATASET_WRITE.value
        )
        resource_type = "dataset"
        keys = ("dataset_id", "table_id", "table_name")
    elif action_id.startswith("asset:"):
        action = CanonicalAction.ASSET_EXECUTE.value
        resource_type = "asset"
        keys = ("asset_id", "asset_key")
    elif action_id.startswith("branch:"):
        action = CanonicalAction.CATALOG_MANAGE.value
        resource_type = "catalog"
        keys = ("branch_name",)
    elif action_id.startswith("workflow:"):
        action = CanonicalAction.OBJECT_WRITE.value
        resource_type = "object"
        keys = ("workflow_id", "path")
    elif action_id.startswith("service:"):
        action = CanonicalAction.SERVICE_MANAGE.value
        resource_type = "service"
        keys = ("service_id", "name")
    else:
        action = CanonicalAction.ADMIN_MANAGE.value
        resource_type = "admin"
        keys = ("name", "package")

    target = body.get("target")
    if isinstance(target, dict):
        target_id = next(
            (target[key] for key in ("id", "name", "key") if isinstance(target.get(key), str)),
            None,
        )
        if target_id:
            # Make the target the only body identity considered by the
            # operation-specific resolver; nested arbitrary IDs are ignored.
            body = {**body, keys[0]: target_id}
            request.state._phlo_security_body_override = body
    return replace(spec, action=action, resource_type=resource_type, resource_keys=keys)


def install_manifest_enforcement(app: Any) -> None:
    """Validate and install the mandatory pre-handler enforcement boundary."""
    validate_manifest(app)

    @app.middleware("http")
    async def _manifest_middleware(request: Request, call_next: Any) -> Any:
        request_id = request.headers.get("x-request-id") or str(uuid4())
        request.state.request_id = request_id
        bind_context(request_id=request_id, path=request.url.path, method=request.method)
        try:
            # CORS preflight is a protocol negotiation request, not an
            # application operation; the actual request remains protected.
            if request.method == "OPTIONS":
                return await call_next(request)
            resolved = _route_for_request(app, request)
            if resolved is None:
                response = await call_next(request)
                response.headers.setdefault("x-request-id", request_id)
                return response
            spec, path_params = resolved
            try:
                await enforce_http_operation(request, spec, path_params)
            except HTTPException as exc:
                detail = exc.detail if isinstance(exc.detail, dict) else {"detail": exc.detail}
                response = JSONResponse(
                    status_code=exc.status_code,
                    content=detail,
                    headers=exc.headers,
                )
                response.headers.setdefault("x-request-id", request_id)
                return response
            except Exception:
                # Authentication and policy resolution are part of the
                # boundary. A provider or backend failure must not reach the
                # handler or become an accidental application 500.
                logger.exception("phlo_api_security_boundary_unavailable")
                response = JSONResponse(
                    status_code=503,
                    content={
                        "error": "service_unavailable",
                        "reason": "authorization_unavailable",
                    },
                )
                response.headers.setdefault("x-request-id", request_id)
                return response
            response = await call_next(request)
            response.headers.setdefault("x-request-id", request_id)
            return response
        finally:
            clear_context()


def validate_operation_registry() -> None:
    """CI-facing validation for duplicate and incomplete non-HTTP entries."""
    names = [
        spec.operation_name for spec in GRAPHQL_OPERATION_MANIFEST + WEBSOCKET_OPERATION_MANIFEST
    ]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise RuntimeError(f"Duplicate GraphQL/WebSocket security operations: {duplicates!r}")
    for spec in GRAPHQL_OPERATION_MANIFEST + WEBSOCKET_OPERATION_MANIFEST:
        if spec.public or not spec.action or not spec.resource_type or not spec.endpoint:
            raise RuntimeError(
                f"Incomplete security operation manifest entry: {spec.operation_name}"
            )


validate_operation_registry()
