"""Capability primitives and registry."""

from typing import TYPE_CHECKING

from phlo.capabilities.interfaces import (
    AlertSink,
    ApiBackend,
    AuthorizationDecision,
    AuthorizationPolicyBackend,
    CatalogScanner,
    DecisionContext,
    MaintenanceReadModel,
    ObservabilityBackend,
    Principal,
    QueryEngine,
    ResourceRef,
    SchemaExtractor,
    SchemaMigrator,
    TableStore,
)
from phlo.capabilities.maintenance import (
    DefaultMaintenanceReadModel,
    MaintenanceOperationStatus,
    MaintenanceStatusSnapshot,
    load_maintenance_status,
    render_maintenance_prometheus,
)
from phlo.capabilities.observability import (
    DefaultObservabilityBackend,
    register_default_capability_providers,
)
from phlo.capabilities.registry import (
    CapabilityRegistry,
    clear_capabilities,
    get_capability_registry,
    register_alert_sink,
    register_api_backend,
    register_asset,
    register_authorization_policy_backend,
    register_catalog,
    register_catalog_scanner,
    register_check,
    register_data_migration_source,
    register_governance_backend,
    register_lineage_sink,
    register_maintenance_read_model,
    register_metadata_catalog,
    register_object_store,
    register_observability_backend,
    register_publish_target,
    register_quality_backend,
    register_query_engine,
    register_resource,
    register_schema_migrator,
    register_table_store,
)
from phlo.capabilities.runtime import (
    RuntimeContext,
    RuntimeRouting,
    resolve_runtime_ref,
    routing_from_context,
)
from phlo.capabilities.specs import (
    AlertSinkSpec,
    ApiBackendSpec,
    AssetCheckSpec,
    AssetSpec,
    AuthorizationPolicyBackendSpec,
    CatalogScannerSpec,
    CatalogSpec,
    CheckResult,
    DataMigrationSourceSpec,
    FieldSpec,
    GovernanceBackendSpec,
    LineageSinkSpec,
    MaintenanceReadModelSpec,
    MaterializeResult,
    MetadataCatalogSpec,
    NormalizedSchema,
    ObjectStoreSpec,
    ObservabilityBackendSpec,
    PartitionSpec,
    PublishTargetSpec,
    QualityBackendSpec,
    QueryEngineSpec,
    ResourceSpec,
    RunResult,
    RunSpec,
    SchemaChange,
    SchemaMigrationPlan,
    SchemaMigrationSpec,
    TableStoreSpec,
)
from phlo.capabilities.support import CapabilitySupport, coerce_capability_support
from phlo.capabilities.telemetry import TelemetryRecorder, get_telemetry_path, iter_telemetry_events

if TYPE_CHECKING:
    from phlo.capabilities.resolver import ResolutionResult

__all__ = [
    "AlertSink",
    "AlertSinkSpec",
    "ApiBackend",
    "ApiBackendSpec",
    "AssetCheckSpec",
    "AssetSpec",
    "AuthorizationDecision",
    "AuthorizationPolicyBackend",
    "AuthorizationPolicyBackendSpec",
    "CatalogSpec",
    "CatalogScanner",
    "CatalogScannerSpec",
    "CapabilitySupport",
    "CapabilityRegistry",
    "CheckResult",
    "DataMigrationSourceSpec",
    "DecisionContext",
    "DefaultMaintenanceReadModel",
    "DefaultObservabilityBackend",
    "FieldSpec",
    "get_telemetry_path",
    "GovernanceBackendSpec",
    "LineageSinkSpec",
    "MaintenanceReadModel",
    "MaintenanceOperationStatus",
    "MaintenanceReadModelSpec",
    "MaintenanceStatusSnapshot",
    "MaterializeResult",
    "MetadataCatalogSpec",
    "NormalizedSchema",
    "ObjectStoreSpec",
    "ObservabilityBackend",
    "ObservabilityBackendSpec",
    "PartitionSpec",
    "Principal",
    "PublishTargetSpec",
    "QueryEngine",
    "QualityBackendSpec",
    "QueryEngineSpec",
    "ResourceRef",
    "ResourceSpec",
    "RunResult",
    "RunSpec",
    "RuntimeContext",
    "RuntimeRouting",
    "SchemaChange",
    "SchemaExtractor",
    "SchemaMigrationPlan",
    "SchemaMigrationSpec",
    "SchemaMigrator",
    "TableStoreSpec",
    "TableStore",
    "coerce_capability_support",
    "clear_capabilities",
    "get_capability_registry",
    "list_capabilities",
    "missing_required_capabilities",
    "register_alert_sink",
    "register_api_backend",
    "register_asset",
    "register_authorization_policy_backend",
    "register_catalog",
    "register_catalog_scanner",
    "register_check",
    "register_data_migration_source",
    "register_governance_backend",
    "register_lineage_sink",
    "register_maintenance_read_model",
    "register_metadata_catalog",
    "register_object_store",
    "register_observability_backend",
    "register_publish_target",
    "register_quality_backend",
    "register_query_engine",
    "register_resource",
    "register_schema_migrator",
    "register_default_capability_providers",
    "register_table_store",
    "ResolutionResult",
    "render_maintenance_prometheus",
    "resolve_runtime_ref",
    "resolve_capability",
    "routing_from_context",
    "TelemetryRecorder",
    "iter_telemetry_events",
    "load_maintenance_status",
]


def __getattr__(name: str):
    """Lazily expose resolver symbols to avoid circular imports."""
    if name in {
        "ResolutionResult",
        "list_capabilities",
        "missing_required_capabilities",
        "resolve_capability",
    }:
        from phlo.capabilities import resolver

        return getattr(resolver, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
