cg_lakehouse:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: /data/duckdb/warehouse.duckdb
      threads: 8
      # Optional: write external parquet by default via configs in models
      extensions: ["httpfs", "json", "parquet"]
      # S3-compatible (MinIO)
      config:
        s3_endpoint: minio:9000
        s3_use_ssl: false
        s3_url_style: path
        s3_access_key_id: "{{ env_var('MINIO_ROOT_USER') }}"
        s3_secret_access_key: "{{ env_var('MINIO_ROOT_PASSWORD') }}"
    postgres:
      type: postgres
      host: postgres
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: marts
      threads: 8
