name: cascade
version: 1.0.0
config-version: 2

profile: cascade

on-run-start:
  - "{{ ducklake__bootstrap() }}"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  cascade:
    +materialized: table
    +database: "{{ env_var('DUCKLAKE_CATALOG_ALIAS', 'dbt') }}"
    bronze:
      +schema: bronze
      +materialized: view
      +tags: ["bronze"]
      +quoting:
        identifier: false
    silver:
      +schema: silver
      +tags: ["silver"]
    gold:
      +schema: gold
      +tags: ["gold"]
      +persist_docs: { relation: true, columns: true }
    marts_postgres:
      +schema: marts
      +tags: ["mart"]
      +materialized: table
