"""Network-free file readers backing the retail Phlo ingestion assets."""

from __future__ import annotations

import json
from pathlib import Path

import dlt
import pandas as pd
import phlo

from workflows.schemas.retail import InventorySchema, ProductsSchema, SalesSchema


def sales_file(partition_date: str, data_dir: Path = Path("data")) -> Path:
    path = data_dir / f"sales_{partition_date}.csv"
    if not path.exists():
        raise FileNotFoundError(f"Missing required store sales file: {path}")
    return path


def read_sales(partition_date: str, data_dir: Path = Path("data")) -> pd.DataFrame:
    frame = pd.read_csv(sales_file(partition_date, data_dir))
    frame["partition_date"] = partition_date
    frame["revenue"] = frame["quantity"] * frame["unit_price"]
    return frame


def read_products(data_dir: Path = Path("data")) -> pd.DataFrame:
    with (data_dir / "products.json").open(encoding="utf-8") as handle:
        return pd.DataFrame(json.load(handle))


def read_inventory(data_dir: Path = Path("data")) -> pd.DataFrame:
    with (data_dir / "inventory.ndjson").open(encoding="utf-8") as handle:
        return pd.DataFrame(json.loads(line) for line in handle if line.strip())


def read_historical_archive(data_dir: Path = Path("data")) -> pd.DataFrame:
    """Read the optional Parquet archive generated by the fixture script."""
    return pd.read_parquet(data_dir / "historical_sales.parquet")


@phlo.ingestion(table_name="retail_sales", unique_key="sale_id", validation_schema=SalesSchema, group="retail")
def retail_sales(partition_date: str) -> object:
    return dlt.resource(read_sales(partition_date).to_dict(orient="records"), name="retail_sales")


@phlo.ingestion(table_name="retail_products", unique_key="product_id", validation_schema=ProductsSchema, group="retail")
def retail_products(partition_date: str) -> object:
    del partition_date
    return dlt.resource(read_products().to_dict(orient="records"), name="retail_products")


@phlo.ingestion(table_name="retail_inventory", unique_key="store_id", validation_schema=InventorySchema, group="retail")
def retail_inventory(partition_date: str) -> object:
    del partition_date
    return dlt.resource(read_inventory().to_dict(orient="records"), name="retail_inventory")
