version: 2

sources:
  - name: dagster_assets
    database: dbt
    schema: raw
    description: Upstream Dagster assets that provide raw data from DuckLake raw layer
    tables:
      - name: entries
        description: Nightscout CGM data ingested via DLT into DuckLake raw.entries
        meta:
          dagster:
            asset_key: ["entries"]
