version: 2

sources:
  - name: dagster_assets
    database: "{{ target.catalog }}"
    schema: raw
    description: Upstream Dagster assets providing raw data from Iceberg via Nessie catalog
    tables:
      - name: entries
        description: Nightscout CGM data ingested via DLT/PyIceberg into Iceberg raw.entries
        meta:
          dagster:
            asset_key: ["entries"]
