version: 2

sources:
  - name: dagster_assets
    # Note: database not specified here - will be set to 'ducklake' at runtime via bootstrap macro
    # This avoids dbt-duckdb trying to validate the database at compile time
    schema: raw
    description: Upstream Dagster assets that provide raw data from DuckLake raw layer
    tables:
      - name: entries
        description: Nightscout CGM data ingested via DLT into DuckLake raw.entries
        meta:
          dagster:
            asset_key: ["entries"]
