version: 2

sources:
  - name: dagster_assets
    database: ducklake
    schema: bronze
    description: Upstream Dagster assets that provide raw data from DuckLake bronze layer
    tables:
      - name: entries
        description: Nightscout CGM data ingested via DLT into DuckLake bronze.entries
        meta:
          dagster:
            asset_key: ["entries"]
