/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as StorageRouteImport } from './routes/storage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as PublishingRouteImport } from './routes/publishing'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LineageRouteImport } from './routes/lineage'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as ExtensionsRouteImport } from './routes/extensions'
import { Route as DatasetsRouteImport } from './routes/datasets'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BiRouteImport } from './routes/bi'
import { Route as ApisRouteImport } from './routes/apis'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsNewRouteImport } from './routes/workflows/new'
import { Route as ExtensionsExtensionIdRouteImport } from './routes/extensions/$extensionId'
import { Route as DatasetsDatasetIdRouteImport } from './routes/datasets.$datasetId'

const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRoute = PublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageRoute = LineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsRoute = ExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetsRoute = DatasetsRouteImport.update({
  id: '/datasets',
  path: '/datasets',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BiRoute = BiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApisRoute = ApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsNewRoute = WorkflowsNewRouteImport.update({
  id: '/workflows/new',
  path: '/workflows/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsExtensionIdRoute = ExtensionsExtensionIdRouteImport.update({
  id: '/$extensionId',
  path: '/$extensionId',
  getParentRoute: () => ExtensionsRoute,
} as any)
const DatasetsDatasetIdRoute = DatasetsDatasetIdRouteImport.update({
  id: '/$datasetId',
  path: '/$datasetId',
  getParentRoute: () => DatasetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apis': typeof ApisRoute
  '/bi': typeof BiRoute
  '/branches': typeof BranchesRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/extensions': typeof ExtensionsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/logs': typeof LogsRoute
  '/observability': typeof ObservabilityRoute
  '/operations': typeof OperationsRoute
  '/pipelines': typeof PipelinesRoute
  '/publishing': typeof PublishingRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tables': typeof TablesRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apis': typeof ApisRoute
  '/bi': typeof BiRoute
  '/branches': typeof BranchesRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/extensions': typeof ExtensionsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/logs': typeof LogsRoute
  '/observability': typeof ObservabilityRoute
  '/operations': typeof OperationsRoute
  '/pipelines': typeof PipelinesRoute
  '/publishing': typeof PublishingRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tables': typeof TablesRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apis': typeof ApisRoute
  '/bi': typeof BiRoute
  '/branches': typeof BranchesRoute
  '/datasets': typeof DatasetsRouteWithChildren
  '/extensions': typeof ExtensionsRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/lineage': typeof LineageRoute
  '/logs': typeof LogsRoute
  '/observability': typeof ObservabilityRoute
  '/operations': typeof OperationsRoute
  '/pipelines': typeof PipelinesRoute
  '/publishing': typeof PublishingRoute
  '/quality': typeof QualityRoute
  '/runs': typeof RunsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/storage': typeof StorageRoute
  '/tables': typeof TablesRoute
  '/datasets/$datasetId': typeof DatasetsDatasetIdRoute
  '/extensions/$extensionId': typeof ExtensionsExtensionIdRoute
  '/workflows/new': typeof WorkflowsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/apis'
    | '/bi'
    | '/branches'
    | '/datasets'
    | '/extensions'
    | '/governance'
    | '/lineage'
    | '/logs'
    | '/observability'
    | '/operations'
    | '/pipelines'
    | '/publishing'
    | '/quality'
    | '/runs'
    | '/services'
    | '/settings'
    | '/storage'
    | '/tables'
    | '/datasets/$datasetId'
    | '/extensions/$extensionId'
    | '/workflows/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/apis'
    | '/bi'
    | '/branches'
    | '/datasets'
    | '/extensions'
    | '/governance'
    | '/lineage'
    | '/logs'
    | '/observability'
    | '/operations'
    | '/pipelines'
    | '/publishing'
    | '/quality'
    | '/runs'
    | '/services'
    | '/settings'
    | '/storage'
    | '/tables'
    | '/datasets/$datasetId'
    | '/extensions/$extensionId'
    | '/workflows/new'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/apis'
    | '/bi'
    | '/branches'
    | '/datasets'
    | '/extensions'
    | '/governance'
    | '/lineage'
    | '/logs'
    | '/observability'
    | '/operations'
    | '/pipelines'
    | '/publishing'
    | '/quality'
    | '/runs'
    | '/services'
    | '/settings'
    | '/storage'
    | '/tables'
    | '/datasets/$datasetId'
    | '/extensions/$extensionId'
    | '/workflows/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApisRoute: typeof ApisRoute
  BiRoute: typeof BiRoute
  BranchesRoute: typeof BranchesRoute
  DatasetsRoute: typeof DatasetsRouteWithChildren
  ExtensionsRoute: typeof ExtensionsRouteWithChildren
  GovernanceRoute: typeof GovernanceRoute
  LineageRoute: typeof LineageRoute
  LogsRoute: typeof LogsRoute
  ObservabilityRoute: typeof ObservabilityRoute
  OperationsRoute: typeof OperationsRoute
  PipelinesRoute: typeof PipelinesRoute
  PublishingRoute: typeof PublishingRoute
  QualityRoute: typeof QualityRoute
  RunsRoute: typeof RunsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  StorageRoute: typeof StorageRoute
  TablesRoute: typeof TablesRoute
  WorkflowsNewRoute: typeof WorkflowsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage': {
      id: '/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof StorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing': {
      id: '/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof PublishingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage': {
      id: '/lineage'
      path: '/lineage'
      fullPath: '/lineage'
      preLoaderRoute: typeof LineageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions': {
      id: '/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof ExtensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datasets': {
      id: '/datasets'
      path: '/datasets'
      fullPath: '/datasets'
      preLoaderRoute: typeof DatasetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bi': {
      id: '/bi'
      path: '/bi'
      fullPath: '/bi'
      preLoaderRoute: typeof BiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apis': {
      id: '/apis'
      path: '/apis'
      fullPath: '/apis'
      preLoaderRoute: typeof ApisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/new': {
      id: '/workflows/new'
      path: '/workflows/new'
      fullPath: '/workflows/new'
      preLoaderRoute: typeof WorkflowsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$extensionId': {
      id: '/extensions/$extensionId'
      path: '/$extensionId'
      fullPath: '/extensions/$extensionId'
      preLoaderRoute: typeof ExtensionsExtensionIdRouteImport
      parentRoute: typeof ExtensionsRoute
    }
    '/datasets/$datasetId': {
      id: '/datasets/$datasetId'
      path: '/$datasetId'
      fullPath: '/datasets/$datasetId'
      preLoaderRoute: typeof DatasetsDatasetIdRouteImport
      parentRoute: typeof DatasetsRoute
    }
  }
}

interface DatasetsRouteChildren {
  DatasetsDatasetIdRoute: typeof DatasetsDatasetIdRoute
}

const DatasetsRouteChildren: DatasetsRouteChildren = {
  DatasetsDatasetIdRoute: DatasetsDatasetIdRoute,
}

const DatasetsRouteWithChildren = DatasetsRoute._addFileChildren(
  DatasetsRouteChildren,
)

interface ExtensionsRouteChildren {
  ExtensionsExtensionIdRoute: typeof ExtensionsExtensionIdRoute
}

const ExtensionsRouteChildren: ExtensionsRouteChildren = {
  ExtensionsExtensionIdRoute: ExtensionsExtensionIdRoute,
}

const ExtensionsRouteWithChildren = ExtensionsRoute._addFileChildren(
  ExtensionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApisRoute: ApisRoute,
  BiRoute: BiRoute,
  BranchesRoute: BranchesRoute,
  DatasetsRoute: DatasetsRouteWithChildren,
  ExtensionsRoute: ExtensionsRouteWithChildren,
  GovernanceRoute: GovernanceRoute,
  LineageRoute: LineageRoute,
  LogsRoute: LogsRoute,
  ObservabilityRoute: ObservabilityRoute,
  OperationsRoute: OperationsRoute,
  PipelinesRoute: PipelinesRoute,
  PublishingRoute: PublishingRoute,
  QualityRoute: QualityRoute,
  RunsRoute: RunsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  StorageRoute: StorageRoute,
  TablesRoute: TablesRoute,
  WorkflowsNewRoute: WorkflowsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
