/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QualityIndexRouteImport } from './routes/quality/index'
import { Route as GraphIndexRouteImport } from './routes/graph/index'
import { Route as BranchesIndexRouteImport } from './routes/branches/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as BranchesBranchNameRouteImport } from './routes/branches/$branchName'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityIndexRoute = QualityIndexRouteImport.update({
  id: '/quality/',
  path: '/quality/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphIndexRoute = GraphIndexRouteImport.update({
  id: '/graph/',
  path: '/graph/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesIndexRoute = BranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesBranchNameRoute = BranchesBranchNameRouteImport.update({
  id: '/branches/$branchName',
  path: '/branches/$branchName',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/branches/$branchName': typeof BranchesBranchNameRoute
  '/assets': typeof AssetsIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/graph': typeof GraphIndexRoute
  '/quality': typeof QualityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/branches/$branchName': typeof BranchesBranchNameRoute
  '/assets': typeof AssetsIndexRoute
  '/branches': typeof BranchesIndexRoute
  '/graph': typeof GraphIndexRoute
  '/quality': typeof QualityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/branches/$branchName': typeof BranchesBranchNameRoute
  '/assets/': typeof AssetsIndexRoute
  '/branches/': typeof BranchesIndexRoute
  '/graph/': typeof GraphIndexRoute
  '/quality/': typeof QualityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets/$assetId'
    | '/branches/$branchName'
    | '/assets'
    | '/branches'
    | '/graph'
    | '/quality'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets/$assetId'
    | '/branches/$branchName'
    | '/assets'
    | '/branches'
    | '/graph'
    | '/quality'
  id:
    | '__root__'
    | '/'
    | '/assets/$assetId'
    | '/branches/$branchName'
    | '/assets/'
    | '/branches/'
    | '/graph/'
    | '/quality/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  BranchesBranchNameRoute: typeof BranchesBranchNameRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  BranchesIndexRoute: typeof BranchesIndexRoute
  GraphIndexRoute: typeof GraphIndexRoute
  QualityIndexRoute: typeof QualityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality/': {
      id: '/quality/'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph/': {
      id: '/graph/'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/': {
      id: '/branches/'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches/$branchName': {
      id: '/branches/$branchName'
      path: '/branches/$branchName'
      fullPath: '/branches/$branchName'
      preLoaderRoute: typeof BranchesBranchNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  BranchesBranchNameRoute: BranchesBranchNameRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  BranchesIndexRoute: BranchesIndexRoute,
  GraphIndexRoute: GraphIndexRoute,
  QualityIndexRoute: QualityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
