#!/usr/bin/env python3
"""Validate container vulnerability waivers and apply Phlo's scan policy."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import subprocess
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any, cast

import yaml

REQUIRED_WAIVER_FIELDS = {
    "id",
    "image",
    "vulnerability_id",
    "severity",
    "reachability",
    "rationale",
    "compensating_control",
    "owner",
    "approval",
    "approval_date",
    "expiry_date",
    "remediation_issue",
}
BLOCKING_SEVERITIES = {"CRITICAL", "HIGH"}
PUBLISHED_SERVICE_REPOSITORIES = {
    "phlo-api": "ghcr.io/phlohouse/phlo-api:",
    "dagster": "ghcr.io/phlohouse/phlo-dagster:",
    "dagster-daemon": "ghcr.io/phlohouse/phlo-dagster:",
    "observatory": "ghcr.io/phlohouse/phlo-observatory:",
}
BROAD_IMAGE_PATHS = {
    ".github/workflows/build-core-services.yml",
    ".github/workflows/container-rescan.yml",
    ".github/workflows/container-security.yml",
    "pyproject.toml",
    "scripts/container_security.py",
    "scripts/generated_image_matrix.py",
    "uv.lock",
}
DIGEST_PATTERN = re.compile(r"sha256:[0-9a-f]{64}")


def _date(value: Any, field: str) -> dt.date:
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    if isinstance(value, str):
        try:
            return dt.date.fromisoformat(value)
        except ValueError as exc:
            raise ValueError(f"{field} must be an ISO date") from exc
    raise ValueError(f"{field} must be an ISO date")


def load_waivers(path: Path) -> list[dict[str, Any]]:
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise ValueError(f"cannot parse waiver register {path}: {exc}") from exc
    if not isinstance(document, dict) or document.get("version") != 1:
        raise ValueError("waiver register must be a mapping with version: 1")
    waivers = document.get("waivers")
    if not isinstance(waivers, list):
        raise ValueError("waiver register must contain a waivers list")
    if not all(isinstance(waiver, dict) for waiver in waivers):
        raise ValueError("every waiver must be a mapping")
    return waivers


def validate_waivers(waivers: list[dict[str, Any]], today: dt.date | None = None) -> list[str]:
    today = today or dt.datetime.now(dt.UTC).date()
    errors: list[str] = []
    active_findings: set[tuple[str, str]] = set()
    ids: set[str] = set()
    for index, waiver in enumerate(waivers, start=1):
        label = str(waiver.get("id") or f"entry {index}")
        missing = sorted(field for field in REQUIRED_WAIVER_FIELDS if not waiver.get(field))
        if missing:
            errors.append(f"{label}: missing required fields: {', '.join(missing)}")
            continue
        if label in ids:
            errors.append(f"{label}: duplicate waiver id")
        ids.add(label)
        severity = str(waiver["severity"]).upper()
        if severity not in BLOCKING_SEVERITIES:
            errors.append(f"{label}: severity must be HIGH or CRITICAL")
        try:
            approved = _date(waiver["approval_date"], f"{label}.approval_date")
            expires = _date(waiver["expiry_date"], f"{label}.expiry_date")
            if expires < approved:
                errors.append(f"{label}: expiry_date precedes approval_date")
            if expires > approved + dt.timedelta(days=30):
                errors.append(f"{label}: waiver duration exceeds 30 days")
            if expires < today:
                errors.append(f"{label}: waiver expired on {expires.isoformat()}")
            else:
                finding = (str(waiver["image"]), str(waiver["vulnerability_id"]))
                if finding in active_findings:
                    errors.append(
                        f"{label}: duplicate active image/finding waiver {finding[0]} / {finding[1]}"
                    )
                active_findings.add(finding)
        except ValueError as exc:
            errors.append(str(exc))
    return errors


def render_waivers(waivers: list[dict[str, Any]], today: dt.date | None = None) -> str:
    today = today or dt.datetime.now(dt.UTC).date()
    groups: dict[str, list[dict[str, Any]]] = {"active": [], "expiring": [], "expired": []}
    for waiver in waivers:
        try:
            expiry = _date(waiver.get("expiry_date"), "expiry_date")
        except ValueError:
            groups["expired"].append(waiver)
            continue
        if expiry < today:
            groups["expired"].append(waiver)
        elif expiry <= today + dt.timedelta(days=7):
            groups["expiring"].append(waiver)
        else:
            groups["active"].append(waiver)

    lines = [
        "<!-- Generated by scripts/container_security.py render-waivers from security/container-waivers.yml; do not edit directly. -->",
        "",
        "# Container vulnerability waivers",
        "",
        "This report is generated from [`container-waivers.yml`](container-waivers.yml).",
        "It records temporary exceptions only. Fixable critical findings, and fixable",
        "high findings in production images, block publication. Critical/high findings",
        "without a fix require an active approved waiver; expired waivers block.",
        "",
    ]
    for title, key in (
        ("Active waivers", "active"),
        ("Expiring within 7 days", "expiring"),
        ("Expired waivers", "expired"),
    ):
        lines.extend((f"## {title}", ""))
        entries = sorted(groups[key], key=lambda item: str(item.get("expiry_date", "")))
        if not entries:
            lines.extend(("None.", ""))
            continue
        lines.extend(
            (
                "| ID | Image/package | Finding | Severity | Owner | Expires | Remediation |",
                "|---|---|---|---|---|---|---|",
            )
        )
        for entry in entries:
            lines.append(
                "| {id} | {image} | {vuln} | {severity} | {owner} | {expires} | {issue} |".format(
                    id=entry.get("id", "invalid"),
                    image=entry.get("image", "invalid"),
                    vuln=entry.get("vulnerability_id", "invalid"),
                    severity=entry.get("severity", "invalid"),
                    owner=entry.get("owner", "invalid"),
                    expires=entry.get("expiry_date", "invalid"),
                    issue=entry.get("remediation_issue", "invalid"),
                )
            )
        lines.append("")
    return "\n".join(lines)


def _image_default(value: str) -> str:
    if value.startswith("${") and ":-" in value and value.endswith("}"):
        return value.split(":-", 1)[1][:-1]
    return value


def affected_images(changed: Iterable[str], root: Path) -> dict[str, list[dict[str, str]]]:
    paths = set(changed)
    service_files = sorted((root / "packages").glob("*/src/*/service.yaml"))
    targets: list[dict[str, str]] = []
    broad_change = any(path in BROAD_IMAGE_PATHS or path.startswith("security/") for path in paths)
    for service_file in service_files:
        service = yaml.safe_load(service_file.read_text(encoding="utf-8"))
        if not isinstance(service, dict) or not isinstance(service.get("build"), dict):
            continue
        package_root = service_file.parents[2]
        relative = package_root.relative_to(root).as_posix()
        if not broad_change and not any(
            path == relative or path.startswith(relative + "/") for path in paths
        ):
            continue
        image = service.get("image")
        if not isinstance(image, str) or not _image_default(image).startswith(
            "ghcr.io/phlohouse/phlo-"
        ):
            continue
        targets.append(
            {
                "service": str(service.get("name", service_file.parent.name)),
                "image": _image_default(image),
                "package": relative,
                # CI uses checked-in Dockerfiles for fast PR feedback. Publication
                # continues to use rendered contexts because service templates may
                # alter their build inputs.
                "context": relative,
                "dockerfile": service_file.parent.relative_to(package_root)
                .joinpath("Dockerfile")
                .as_posix(),
            }
        )
    return {"include": targets}


def published_fleet(root: Path) -> list[dict[str, Any]]:
    """Derive and validate the complete unique published fleet from service source."""
    by_service: dict[str, str] = {}
    for service_file in sorted((root / "packages").glob("*/src/*/*.yaml")):
        service = yaml.safe_load(service_file.read_text(encoding="utf-8"))
        if not isinstance(service, dict) or not isinstance(service.get("build"), dict):
            continue
        service_name = service.get("name")
        image = service.get("image")
        if not isinstance(service_name, str) or not isinstance(image, str):
            raise ValueError(f"built service in {service_file} has invalid name or image")
        image = _image_default(image).split("@", 1)[0]
        if service_name in by_service:
            raise ValueError(f"duplicate published service {service_name!r}")
        by_service[service_name] = image

    expected_services = set(PUBLISHED_SERVICE_REPOSITORIES)
    actual_services = set(by_service)
    if actual_services != expected_services:
        missing = sorted(expected_services - actual_services)
        unexpected = sorted(actual_services - expected_services)
        raise ValueError(
            f"published service fleet mismatch; missing={missing!r}, unexpected={unexpected!r}"
        )
    for service_name, repository in PUBLISHED_SERVICE_REPOSITORIES.items():
        if not by_service[service_name].startswith(repository):
            raise ValueError(
                f"published service {service_name!r} must use a versioned {repository!r} image"
            )
    if by_service["dagster"] != by_service["dagster-daemon"]:
        raise ValueError("dagster and dagster-daemon must share one published image")

    grouped: dict[str, list[str]] = {}
    for service_name, image in by_service.items():
        grouped.setdefault(image, []).append(service_name)
    if len(grouped) != 3:
        raise ValueError(
            f"published fleet must contain exactly three unique images, found {len(grouped)}"
        )
    return [
        {"image": image, "services": sorted(services)}
        for image, services in sorted(grouped.items())
    ]


def assemble_rescan_manifest(records: Any, root: Path) -> list[dict[str, Any]]:
    """Validate resolved registry records against source and return a stable manifest."""
    if not isinstance(records, list):
        raise ValueError("resolved registry records must be a list")
    expected = {entry["image"]: entry["services"] for entry in published_fleet(root)}
    resolved: dict[str, dict[str, Any]] = {}
    seen_services: set[str] = set()
    for index, raw_record in enumerate(records, start=1):
        if not isinstance(raw_record, dict) or set(raw_record) != {"image", "digest", "services"}:
            raise ValueError(f"resolved registry record {index} is malformed")
        record = cast(dict[str, Any], raw_record)
        image = record["image"]
        digest = record["digest"]
        services = record["services"]
        if (
            not isinstance(image, str)
            or not isinstance(digest, str)
            or DIGEST_PATTERN.fullmatch(digest) is None
            or not isinstance(services, list)
            or not services
            or not all(isinstance(service, str) and service for service in services)
            or len(services) != len(set(services))
        ):
            raise ValueError(f"resolved registry record {index} is malformed")
        if image in resolved:
            raise ValueError(f"duplicate resolved registry image {image!r}")
        normalized_services = sorted(services)
        conflicting = seen_services.intersection(normalized_services)
        if conflicting:
            raise ValueError(f"services mapped to multiple images: {sorted(conflicting)!r}")
        seen_services.update(normalized_services)
        resolved[image] = {
            "image": image,
            "digest": digest,
            "services": normalized_services,
        }

    if set(resolved) != set(expected):
        missing = sorted(set(expected) - set(resolved))
        unexpected = sorted(set(resolved) - set(expected))
        raise ValueError(
            f"resolved image fleet mismatch; missing={missing!r}, unexpected={unexpected!r}"
        )
    for image, services in expected.items():
        if resolved[image]["services"] != services:
            raise ValueError(
                f"resolved image {image!r} has services {resolved[image]['services']!r}; "
                f"expected {services!r}"
            )
    return [resolved[image] for image in sorted(resolved)]


def _waived(waivers: list[dict[str, Any]], image: str, vulnerability_id: str) -> bool:
    image_name = image.split("@", 1)[0]
    for waiver in waivers:
        if str(waiver.get("vulnerability_id")) != vulnerability_id:
            continue
        candidate = str(waiver.get("image"))
        if candidate in (image, image_name) or image_name.startswith(candidate + ":"):
            return True
    return False


def apply_policy(report: dict[str, Any], image: str, waivers: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    for result in report.get("Results", []) or []:
        for finding in result.get("Vulnerabilities", []) or []:
            severity = str(finding.get("Severity", "")).upper()
            vulnerability_id = str(finding.get("VulnerabilityID", "unknown"))
            fixed = bool(finding.get("FixedVersion"))
            production = image.split("@", 1)[0].startswith("ghcr.io/phlohouse/phlo-")
            blocks = severity == "CRITICAL" or (severity == "HIGH" and production)
            if not blocks:
                continue
            if fixed:
                errors.append(
                    f"{image}: fixable {severity} {vulnerability_id} (fixed in {finding['FixedVersion']})"
                )
            elif not _waived(waivers, image, vulnerability_id):
                errors.append(
                    f"{image}: unfixed {severity} {vulnerability_id} requires an active waiver"
                )
    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    validate = sub.add_parser("validate-waivers")
    validate.add_argument("--register", type=Path, default=Path("security/container-waivers.yml"))
    render = sub.add_parser("render-waivers")
    render.add_argument("--register", type=Path, default=Path("security/container-waivers.yml"))
    render.add_argument("--output", type=Path, default=Path("security/container-waivers.md"))
    affected = sub.add_parser("affected-images")
    changed_scope = affected.add_mutually_exclusive_group(required=True)
    changed_scope.add_argument("--base")
    changed_scope.add_argument(
        "--all",
        action="store_true",
        help="Return every generated service image for the nightly validation lane.",
    )
    affected.add_argument("--head", default="HEAD")
    fleet = sub.add_parser("published-fleet")
    fleet.add_argument("--root", type=Path, default=Path.cwd())
    assemble = sub.add_parser("assemble-rescan-manifest")
    assemble.add_argument("--records", type=Path, required=True)
    assemble.add_argument("--output", type=Path, required=True)
    assemble.add_argument("--root", type=Path, default=Path.cwd())
    policy = sub.add_parser("apply-policy")
    policy.add_argument("--register", type=Path, default=Path("security/container-waivers.yml"))
    policy.add_argument("--image", required=True)
    policy.add_argument("--report", type=Path, required=True)
    args = parser.parse_args()
    if args.command == "published-fleet":
        print(json.dumps(published_fleet(args.root), separators=(",", ":")))
        return 0
    if args.command == "assemble-rescan-manifest":
        manifest = assemble_rescan_manifest(
            json.loads(args.records.read_text(encoding="utf-8")), args.root
        )
        args.output.write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        return 0
    if args.command == "affected-images":
        if args.all:
            changed = ["pyproject.toml"]
        else:
            changed = subprocess.check_output(
                ["git", "diff", "--name-only", f"{args.base}...{args.head}"], text=True
            ).splitlines()
        print(json.dumps(affected_images(changed, Path.cwd()), separators=(",", ":")))
        return 0
    waivers = load_waivers(args.register)
    if args.command == "validate-waivers":
        errors = validate_waivers(waivers)
        if errors:
            print(
                "Container waiver register validation failed:",
                *[f"- {error}" for error in errors],
                sep="\n",
                file=sys.stderr,
            )
            return 1
        return 0
    if args.command == "render-waivers":
        args.output.write_text(render_waivers(waivers), encoding="utf-8")
        return 0
    errors = validate_waivers(waivers) + apply_policy(
        json.loads(args.report.read_text(encoding="utf-8")), args.image, waivers
    )
    if errors:
        print(
            "Container vulnerability policy failed:",
            *[f"- {error}" for error in errors],
            sep="\n",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
