"""
Compose Generator Module

Generates docker-compose.yml and .env/.env.local files from service definitions.
"""

import os
import platform
import shutil
from pathlib import Path
from typing import Any, Literal

import yaml

from phlo.logging import get_logger
from phlo.plugins.compose.env import (
    generate_env as _generate_env,
)
from phlo.plugins.compose.env import (
    generate_env_local as _generate_env_local,
)
from phlo.plugins.discovery import ServiceDefinition, ServiceDiscovery

logger = get_logger(__name__)


_PRODUCTION_INTERNAL_SERVICES = frozenset({"postgres", "minio", "nessie", "trino", "dagster"})
_PRODUCTION_CREDENTIAL_DEFAULTS = {
    "POSTGRES_USER": "phlo",
    "POSTGRES_PASSWORD": "phlo",
    "MINIO_ROOT_USER": "minio",
    "MINIO_ROOT_PASSWORD": "minio123",
}


class ComposeGenerator:
    """Generates docker-compose.yml from service definitions."""

    def __init__(self, discovery: ServiceDiscovery):
        """Initialize with a service discovery instance."""
        self.discovery = discovery

    def generate_compose(
        self,
        services: list[ServiceDefinition],
        output_dir: Path,
        dev_mode: bool = False,
        service_dev_mode: bool = False,
        phlo_src_path: str | None = None,
        user_overrides: dict[str, Any] | None = None,
        deployment_profile: Literal["development", "production"] = "development",
    ) -> str:
        """Generate docker-compose.yml content.

        Args:
            services: List of services to include.
            output_dir: Target directory (for resolving relative paths).
            dev_mode: If True, add phlo source mounts for dev services.
            service_dev_mode: If True, apply service-specific `dev:` overrides.
            phlo_src_path: Path to phlo source (relative to project root).
            user_overrides: Dict of service name to ServiceOverride config from phlo.yaml.
            deployment_profile: Deployment posture for generated service bindings.

        Returns:
            Docker compose YAML content as string.
        """
        # Sort services by dependencies
        sorted_services = self.discovery.resolve_dependencies(services)
        user_overrides = user_overrides or {}

        compose: dict[str, Any] = {"services": {}}

        for service in sorted_services:
            # Get user override for this service (if any)
            service_override = user_overrides.get(service.name, {})

            compose["services"][service.name] = self._build_service_config(
                service,
                output_dir,
                dev_mode=dev_mode,
                service_dev_mode=service_dev_mode,
                phlo_src_path=phlo_src_path,
                user_override=service_override,
            )
            if deployment_profile == "production":
                self._apply_production_profile(service.name, compose["services"][service.name])

        named_volumes = self._collect_named_volumes(compose["services"].values())
        if named_volumes:
            compose["volumes"] = {name: {} for name in sorted(named_volumes)}

        # Add header comment with dev mode flag for stale detection
        dev_mode_str = "true" if dev_mode else "false"
        header = f"""# Phlo Infrastructure Stack
# Generated by: phlo services init
# Dev mode: {dev_mode_str}
# Modify phlo.yaml (env:) for defaults and .phlo/.env.local for secrets

"""
        return header + yaml.dump(compose, default_flow_style=False, sort_keys=False)

    def _apply_production_profile(self, service_name: str, config: dict[str, Any]) -> None:
        """Apply the bounded production network and credential posture."""
        if service_name in _PRODUCTION_INTERNAL_SERVICES:
            config.pop("ports", None)
        self._require_production_credentials(config)

    def _require_production_credentials(self, value: Any) -> Any:
        """Replace bundled credential fallbacks with Compose required-variable syntax."""
        if isinstance(value, dict):
            for key, nested_value in value.items():
                value[key] = self._require_production_credentials(nested_value)
            return value
        if isinstance(value, list):
            return [self._require_production_credentials(item) for item in value]
        if not isinstance(value, str):
            return value

        for variable, default in _PRODUCTION_CREDENTIAL_DEFAULTS.items():
            bundled = f"${{{variable}:-{default}}}"
            if bundled in value:
                required = f"${{{variable}:?Phlo production requires {variable}}}"
                value = value.replace(bundled, required)
        return value

    def _collect_named_volumes(self, services: Any) -> set[str]:
        """Collect named service volumes that need top-level compose declarations."""
        named_volumes: set[str] = set()
        for service in services:
            for volume in service.get("volumes", []):
                name = self._named_volume_from_mount(volume)
                if name:
                    named_volumes.add(name)
        return named_volumes

    def _named_volume_from_mount(self, volume: Any) -> str | None:
        """Return the named volume source for a short-syntax mount, if any."""
        if not isinstance(volume, str) or ":" not in volume:
            return None

        # Check for Windows drive-letter prefix (e.g., "C:\path")
        if len(volume) >= 2 and volume[0].isalpha() and volume[1] == ":":
            return None

        source = volume.split(":", 1)[0]
        if not source:
            return None
        if source.startswith((".", "/", "~", "$", "{")):
            return None
        if source.startswith("${"):
            return None

        return source

    def _build_service_config(
        self,
        service: ServiceDefinition,
        output_dir: Path,
        dev_mode: bool = False,
        service_dev_mode: bool = False,
        phlo_src_path: str | None = None,
        user_override: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Build docker-compose service configuration.

        Args:
            service: Service definition from package/core.
            output_dir: Output directory for relative paths.
            dev_mode: Whether to add Phlo source mounts for dev workflows.
            service_dev_mode: Whether to apply service-specific `dev:` runtime overrides.
            phlo_src_path: Path to phlo source.
            user_override: User overrides from phlo.yaml services section.
        """
        config: dict[str, Any] = {}
        user_override = user_override or {}

        # Image or build
        if service.image:
            config["image"] = service.image
        elif service.build:
            # Determine build context
            context = service.build.get("context", ".")
            if context == "source" and service.source_path:
                # Use the service's source directory as build context
                context = str(service.source_path)
            if isinstance(context, str):
                context_path = Path(context)
                if context_path.is_absolute():
                    context = os.path.relpath(context_path, output_dir)
            build_config: dict[str, Any] = {"context": context}
            if service.build.get("dockerfile"):
                build_config["dockerfile"] = service.build["dockerfile"]
            if service.build.get("args"):
                build_config["args"] = service.build["args"]
            config["build"] = build_config

        # Profile (if not default)
        if service.profile:
            config["profiles"] = [service.profile]

        # Compose configuration
        compose = service.compose

        config["restart"] = compose.get("restart", "unless-stopped")

        handled_compose_keys = {
            "restart",
            "volumes",
            "command",
            "entrypoint",
            "healthcheck",
            "profiles",
            "env_file",
            "build",
            "depends_on",
        }

        for key in ("user", "container_name", "labels", "environment", "ports"):
            if compose.get(key):
                config[key] = compose[key]
                handled_compose_keys.add(key)

        if compose.get("volumes"):
            config["volumes"] = list(compose["volumes"])  # Copy to avoid mutation
        else:
            config["volumes"] = []

        # Dev mode: inject phlo source mount and project directory for dependency sync
        if dev_mode and service.phlo_dev and phlo_src_path:
            # Mount the phlo monorepo root for editable installs inside the container.
            # `phlo_src_path` points at `.../src/phlo`, so `../..` is the repo root.
            project_mount = f"{phlo_src_path}/../..:/opt/phlo-dev:rw"
            config["volumes"].append(project_mount)
            # Add environment variable to enable dev mode sync
            if "environment" not in config:
                config["environment"] = {}
            if isinstance(config["environment"], dict):
                config["environment"]["PHLO_DEV_MODE"] = "true"
            elif isinstance(config["environment"], list):
                config["environment"].append("PHLO_DEV_MODE=true")

        # Remove empty volumes list
        if not config["volumes"]:
            del config["volumes"]

        if service_dev_mode and service.dev:
            self._apply_dev_overrides(config, service, output_dir)

        # Add env_file for phlo_dev services to pick up project secrets (e.g., GITHUB_TOKEN)
        # Path is relative to .phlo/ directory where docker-compose.yml lives
        if service.phlo_dev:
            config["env_file"] = [".env", ".env.local"]

        if compose.get("command"):
            config["command"] = compose["command"]

        if compose.get("entrypoint"):
            config["entrypoint"] = compose["entrypoint"]

        if compose.get("healthcheck"):
            config["healthcheck"] = compose["healthcheck"]

        # Pass through remaining compose keys such as mem_limit/cpus/ulimits.
        # This keeps generator behavior future-proof for valid docker-compose options.
        for key, value in compose.items():
            if key in handled_compose_keys:
                continue
            if value is None:
                continue
            config[key] = value

        if service.name in {"dagster", "dagster-daemon"}:
            if platform.system() == "Linux":
                config["user"] = f"{os.getuid()}:{os.getgid()}"
                environment = config.setdefault("environment", {})
                if isinstance(environment, dict):
                    environment.setdefault("HOME", "/opt/dagster")
                elif isinstance(environment, list) and not any(
                    item.startswith("HOME=") for item in environment if isinstance(item, str)
                ):
                    environment.append("HOME=/opt/dagster")
            else:
                config.pop("user", None)

        # Dependencies
        if service.depends_on:
            depends_config: dict[str, dict[str, str]] = {}
            for dep in service.depends_on:
                dep_service = self.discovery.get_service(dep)
                if dep_service:
                    if dep.endswith("-setup"):
                        depends_config[dep] = {"condition": "service_completed_successfully"}
                    elif dep_service.compose.get("healthcheck"):
                        depends_config[dep] = {"condition": "service_healthy"}
                    else:
                        depends_config[dep] = {"condition": "service_started"}
            if depends_config:
                config["depends_on"] = depends_config

        # Apply user overrides from phlo.yaml (last, so they take precedence)
        self._apply_user_overrides(config, user_override)

        return config

    def _apply_user_overrides(
        self,
        config: dict[str, Any],
        user_override: dict[str, Any],
    ) -> None:
        """Apply user overrides from phlo.yaml services section.

        Override behavior:
        - ports: replaces package default
        - environment: merges (user values override package)
        - volumes: appends to package defaults
        - depends_on: replaces package default
        - command: replaces package default
        """
        if not user_override:
            return

        # Ports: replace
        if user_override.get("ports"):
            config["ports"] = user_override["ports"]

        # Environment: merge (user takes precedence)
        if user_override.get("environment"):
            config.setdefault("environment", {})
            if isinstance(config["environment"], list):
                # Convert list format to dict then merge
                config["environment"] = dict(
                    item.split("=", 1) for item in config["environment"] if "=" in item
                )
            config["environment"].update(user_override["environment"])

        # Volumes: append
        if user_override.get("volumes"):
            config.setdefault("volumes", [])
            config["volumes"].extend(user_override["volumes"])

        # Depends on: replace
        if user_override.get("depends_on"):
            config["depends_on"] = {
                dep: {"condition": "service_started"} for dep in user_override["depends_on"]
            }

        # Command: replace
        if user_override.get("command"):
            config["command"] = user_override["command"]

        # Healthcheck: replace (for inline services)
        if user_override.get("healthcheck"):
            config["healthcheck"] = user_override["healthcheck"]

    def _apply_dev_overrides(
        self,
        config: dict[str, Any],
        service: ServiceDefinition,
        output_dir: Path,
    ) -> None:
        dev = service.dev

        # Dev build: replace image with build context
        if dev.get("build"):
            # Remove image if present (we're building from source now)
            if "image" in config:
                del config["image"]

            build_ctx = dev["build"].get("context", ".")
            # Resolve {source} placeholder
            if "{source}" in build_ctx and service.source_path:
                build_ctx = os.path.relpath(service.source_path, output_dir)

            config["build"] = {
                "context": build_ctx,
                "dockerfile": dev["build"].get("dockerfile", "Dockerfile"),
            }

        if dev.get("environment"):
            config.setdefault("environment", {})
            if isinstance(config["environment"], dict):
                config["environment"].update(dev["environment"])
        if dev.get("command"):
            config["command"] = dev["command"]
        if dev.get("entrypoint"):
            config["entrypoint"] = dev["entrypoint"]
        if dev.get("ports"):
            config["ports"] = dev["ports"]
        if dev.get("volumes"):
            config["volumes"] = [
                self._resolve_dev_volume(volume, service, output_dir) for volume in dev["volumes"]
            ]

    def _resolve_dev_volume(
        self,
        volume: str,
        service: ServiceDefinition,
        output_dir: Path,
    ) -> str:
        if not service.source_path:
            return volume
        source_path = str(os.path.relpath(service.source_path, output_dir))
        resolved = volume
        if "{source}" in resolved:
            resolved = resolved.replace("{source}", source_path)
        if "{source_path}" in resolved:
            resolved = resolved.replace("{source_path}", source_path)
        return resolved

    def generate_env(
        self,
        services: list[ServiceDefinition],
        env_overrides: dict[str, Any] | None = None,
    ) -> str:
        """Generate .env file content (non-secret defaults)."""
        return _generate_env(services, env_overrides=env_overrides)

    def generate_env_local(
        self,
        services: list[ServiceDefinition],
        env_overrides: dict[str, Any] | None = None,
        existing_values: dict[str, str] | None = None,
    ) -> str:
        """Generate .env.local file content (secrets and local overrides)."""
        return _generate_env_local(
            services, env_overrides=env_overrides, existing_values=existing_values
        )

    def copy_service_files(
        self,
        services: list[ServiceDefinition],
        output_dir: Path,
    ) -> list[str]:
        """Copy additional files required by services.

        Args:
            services: List of services.
            output_dir: Target .phlo directory.

        Returns:
            List of copied file paths.
        """
        copied: list[str] = []

        for service in services:
            if not service.files or not service.source_path:
                continue

            for file_spec in service.files:
                source = service.source_path / file_spec["source"]
                dest = output_dir / file_spec["dest"]

                if not source.exists():
                    logger.warning(
                        "compose_service_file_source_missing",
                        service_name=service.name,
                        source=str(source),
                        destination=str(dest),
                    )
                    continue

                # Create parent directories
                dest.parent.mkdir(parents=True, exist_ok=True)

                # Copy file or directory
                if source.is_dir():
                    if dest.exists():
                        shutil.rmtree(dest)
                    shutil.copytree(source, dest)
                else:
                    shutil.copy2(source, dest)

                copied.append(str(dest.relative_to(output_dir)))

        return copied

    def generate_gitignore(self, services: list[ServiceDefinition]) -> str:
        """Generate .gitignore content for .phlo directory."""
        entries: list[str] = [
            "# Phlo infrastructure files",
            ".env",
            ".env.local",
            "volumes/",
        ]

        extra_entries: list[str] = []
        for service in services:
            for entry in service.gitignore:
                if entry not in extra_entries:
                    extra_entries.append(entry)

        if extra_entries:
            entries.append("")
            entries.append("# Service runtime data")
            entries.extend(extra_entries)

        return "\n".join(entries) + "\n"
